apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: result-server-deploy
  name: result-server-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-server-deploy
  template:
    metadata:
      labels:
        app: result-server-deploy
    spec:
      containers:
      - image: kodal035/result-server
        name: result-server-deploy
        ports:
          - containerPort: 80
        env:
          - name: MYSQL_DATABASE_HOST
            value: "mysql"  
          - name: MYSQL_DATABASE
            value: "phonebook"
          - name: MYSQL_USER
            value: "kodal035"
          - name: MYSQL_PASSWORD
            value: "sifre.12345"